# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Knowledgepad
organisation: Matt Grey

description: >- # this means to ignore newlines until "baseurl:"
  Find all the necessary templates and guidelines that make up the Alliants brand identity.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty # default permalink format

# Build settings
markdown: kramdown

plugins:
  # No plugins

sass:
  style: compressed # :nested :compact :expanded :compressed

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Structure
collections:
  resource-docs:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: resource-docs
    values:
      layout: resource
      permalink: /resource/:categories/:name/

# Top level navigation:
parent-site: # If you would like to highlighted link to a main business website that you visited this resource from
  label: View project on Github
  url: //github.com/MattGreyDesign/Knowledgepad

navigation:
  # - label: One
  #   url: /one
  # - label: Two
  #   url: /two

# Appearance
site-accent-color: '#409ADC' #used by SCSS ($site-accent-color) and Liquid ({{ site.site-accent-color }})
